.PHONY: up down logs build migrate revision seed test lint fmt backend-shell

up:            ## Start full stack
	docker compose up -d --build

down:          ## Stop stack
	docker compose down

logs:          ## Tail all logs
	docker compose logs -f

build:         ## Build images
	docker compose build

migrate:       ## Apply DB migrations
	docker compose exec api alembic upgrade head

revision:      ## Create a new autogenerated migration: make revision m="message"
	docker compose exec api alembic revision --autogenerate -m "$(m)"

seed:          ## Seed demo tenant + admin user
	docker compose exec api python -m app.scripts.seed

smoke:         ## End-to-end smoke test (stack must be up)
	docker compose exec api python -m app.scripts.smoke_test

test:          ## Run backend tests
	docker compose exec api pytest -q

lint:          ## Lint backend
	docker compose exec api ruff check app

fmt:           ## Format backend
	docker compose exec api ruff format app

backend-shell: ## Shell into api container
	docker compose exec api bash
